Add notebook that can update the workshop materials
Unidata/pyaos-ams-2021 pull request #77
Opened 2021-01-06 13:40 UTC by lesserwhirls

Add a notebook that users can run to update their copy of the workshop material without needing to run the command on the command line. The notebook lives in `.internal/`, and will ultimately be copied into the workshop participants top level user directory (one level up from the local git repository holding the workshop material).

2021-01-06 23:29 UTC, dopplershift approved these changes

2021-01-08 00:52 UTC, julienchastang approved these changes

2021-01-08 00:53 UTC, julienchastang commented
Nice work!

2021-01-08 00:56 UTC, julienchastang requested changes
I suggest putting this at the root of the repo so that it is easy for users to find.

Never mind. See above comment.

2021-01-08 00:58 UTC, julienchastang approved these changes

2021-01-08 00:59 UTC, merged